### ISSUE TITLE
Foreign key naming

### ISSUE THREAD

**Issue by btxtiger** [tonivj5/typeorm-naming-strategies#1]
I think it is not useful to automatically attach the referenced column name for FK column names, because it generates inconsistency of the property names and makes ist more difficult to find(out) the correct column name when referencing e.g. in where clause.
Example: FK property `ofUserId` would currently be renamed to `of_user_id_user_id`
and in my code I need to reference on this renaming
```ts
.where('user.of_user_id_user_id = :userId', { userId: userId })
```
Better:
```ts
.where('user.of_user_id = :user_id', { userId: userId })
```
TypeORM in general is here a litte bit unhandy in my opinion, because column names need to be hardcoded and this is really not useful when working with naming strategies. A simple workaround could be to provide a function that returns the correct column name, like `col(User.userId)`, which can consider active naming strategies and for e.g. SnakeCase return `user.user_id` or `user.userId` for default config. But this way, the code is a lot easier to refactor.

Nice to have:
```ts
.where(col(User.userId) + '= :userId', { userId: userId })
// or
.where(col(User.userId), { userId: userId })
```

**Comment by xxxtonixxx** [comment]
Hi @btxtiger, using the query builder you do not need to write the name of the column like it's in the database, you can put it as it's declared in your class.

For example, if your User class has a property ofUser (I'm supposing how it's your implementation):
```ts
class User {
    @PrimaryGeneratedColumn()
    id: number
    @OneToOne(() => User)
    @JoinColumn()
    ofUser: User
}
```
typeorm generates an `of_user_id` FK (if your PR is `userId`, it would be more verbose, `of_user_user_id`), but in any case, you should not worry about the column name in your db, because you can use the property name to do the query instead of the column name generated :fire::
```ts
const user = await userRepository.createQueryBuilder('user')
                             .where('user.ofUser = :userId', {userId: 1}).getOne();
```

I think that's your problem, if I'm misunderstanding you, I'm sorry! :laughing:

**Comment by btxtiger** [comment]
> using the query builder you do not need to write the name of the column like it's in the database, you can put it as it's declared in your class.

Indeed, there was another mistake which prevented it from working. Thanks for explanation!

> typeorm generates an of_user_id FK (if your PR is userId, it would be more verbose, of_user_user_id), but in any case, you should not worry about the column name in your db, because you can use the property name to do the query instead of the column name generated

Thats correct, but if you need to use `.getRawMany` and `.getRawOne` because of using for example subselects, you would get a diverging name as property. It also deprives a bit the control of the programmer, because just using an ORM does not always mean "I don't want do handle the database by myself", especially when using a custom naming strategy. Otherwise i could just use the default settings.

Currently I wrote a cleanup method to get usable data from the `.getRaw` methods.
E.g. `message_last_modified` -> `lastModified`, as it would be without naming strategy.
It just camelCases all properties and optionally removes any table prefixes. If you might find that useful for adding to the snake naming strategy class, I could open a pull request for that.
```ts
public static cleanupGetRaw(rawData: RawDataObject | Array<RawDataObject>, deletePrefixes: Array<string> = []): any
```

**Comment by xxxtonixxx** [comment]
I think it's interesting, however I have not that problem. How would its use? Can you show me an example?
```ts
const data = SnakeNamingStrategy.cleanupGetRaw(await db.builder(...).getRaw()); // Is it?
```

**Comment by btxtiger** [comment]
Actually thats all:

```ts
let data = await (...).getRawMany();
/*
{
   user_id: 12,
   user_full_name: "Peter Shaw",
   userProfile_picture_url: "http:// ...."
}
*/

data = SnakeNamingStrategy.cleanupGetRaw(data, ['user', 'userProfile']);
/*
   id: 12,
   fullName: "Peter",
   pictureUrl: "http://"
*/
```

```ts
import { camelCase, snakeCase } from 'typeorm/util/StringUtils';

interface RawData {
   [key: string]: any;
}

/**
    * Cleanup response objects from .getRawMany and .getRawOne
    * @param rawData
    * @param deletePrefixes
    */
   public static cleanupGetRaw(rawData: RawData | Array<RawData>, deletePrefixes: Array<string> = []): any {
      let newName: string, prefixStr: string;

      const cleanupRow = (row: RawData) => {
         for (const prop in row) {
            if (row.hasOwnProperty(prop)) {
               newName = prop;
               deletePrefixes.map(prefix => {
                  prefixStr = prefix + '_';
                  if (newName.startsWith(prefixStr)) {
                     newName = newName.replace(prefixStr, '');
                  }
               });
               newName = camelCase(newName);
               this.renameObjectProperty(row, prop, newName);
            }
         }
      };

      // Support array or single object
      if (rawData instanceof Array) {
         for (const row of rawData) {
            cleanupRow(row);
         }
      } else {
         cleanupRow(rawData);
      }

      return rawData;
   }

   /**
    * Rename property in object
    * https://stackoverflow.com/questions/4647817/javascript-object-rename-key
    * @param obj
    * @param oldKey
    * @param newKey
    */
   public static renameObjectProperty(obj: any, oldKey: string, newKey: string): any {
      if (oldKey !== newKey) {
         Object.defineProperty(obj, newKey, Object.getOwnPropertyDescriptor(obj, oldKey));
         delete obj[oldKey];
      }
   }
```

**Comment by btxtiger** [comment]
I'm running again into that naming issue. Can't it be possible that there is really one?
```ts
getRepository(PublicChannelMessage)
    .createQueryBuilder('message')
    .select()
    .addSelect(qb => {
        return qb
            .select('SUM(vote1.weight)', 'total')
            .from('public_channel_message_vote', 'vote1')
            .leftJoin('public_channel_message', 'message1', 'vote1.ofMessage = message1.publicChannelMessageId')
            .where('vote1.ofMessage = message.publicChannelMessageId');
    }, 'totalWeight')
    .where('message.ofChannel = :id', { id: channelId })
    .getRawMany()
```

The issue occurres for subqueries. When I'm writing the camelCase name, the query will fail. Outside the subquery it works as usual.
`.from('publicChannelMessageVote'`
`.leftJoin('publicChannelMessage'`
```sql
 code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage:
   'Table \'chat_orm.publicchannelmessagevote\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
```

**Comment by xxxtonixxx** [comment]
Hi @btxtiger, I'm trying to replicate your error but I can't. I'm using a subquery as you and it's working like it's expected :confused:

**Comment by xxxtonixxx** [comment]
Anyway, If it's failing It's an error of typeorm, because the expected behavior is that translate the camelCase name to snake_case. Are you sure that your table is registered or that's the correct name?
