### ISSUE TITLE
Typeorm v0.3.3 support

### ISSUE THREAD

**Issue by mikededo** [tonivj5/typeorm-naming-strategies#27]
The `package.json` file has already been updated to support v0.3.3 of `typeorm`, but no release has been created.

When will the realease be made, with the updated dependencies?

Thanks 😄

**Comment by tonivj5** [comment]
Just released at `4.1.0`! 

Ref: https://github.com/tonivj5/typeorm-naming-strategies/pull/24#issuecomment-1080013600
