### ISSUE TITLE
Naming Strategy and Migration Files

### ISSUE THREAD

**Issue by qathom** [tonivj5/typeorm-naming-strategies#4]
Hello,

Thanks for making `typeorm-naming-strategies`!

I'd like to report something that I identified.
If we generate a migration file, the columns are not in snake case format.
For the moment, I didn't spend time to investigate more about this but I wanted to report this as a first step.

Steps:

1. Run `typeorm migration:generate -n MyMigrationFile`
2. Open the generated file. Typeorm doesn't convert in Snake case. Expecting `created_at`instead of `createdAt`:

```ts
import { MigrationInterface, QueryRunner } from 'typeorm';

export class MyMigrationFile1596812506458 implements MigrationInterface {
  name = 'MyMigrationFile1596812506458'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("ALTER TABLE `my_entity` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
```

Entity sample (`test.entity.ts`):

```ts
import { Entity, PrimaryGeneratedColumn, CreateDateColumn } from 'typeorm';

@Entity()
export class MyEntity {
  @PrimaryGeneratedColumn('increment')
  id: number;

  @CreateDateColumn()
  createdAt: Date;
}
```

**Comment by tonivj5** [comment]
Hey @qathom, glad to hear someone else is using this module :tada:

To use it into migrations, you must import it too. See this issue where explain how to do it https://github.com/typeorm/typeorm/issues/1482#issuecomment-375074245 or this one https://github.com/typeorm/typeorm/issues/2200#issuecomment-511037158

I hope this works for you :+1:

**Comment by ofbeaton** [comment]
I came here looking for a solution to this problem as well. Perhaps the proper solution would be to update this modules usage documentation to cover this? I also expected it to cover this.

**Comment by qathom** [comment]
Hi @tonivj5 

Thanks for your prompt reply!
This module should be an official option in typeorm because case sensitivity can be an issue (at least tables) :-)

I understand that we have to import this module - sadly I'm using the typeorm CLI directly so this means that I would need to setup a "wrapper" or as you suggested, use a js config file.
Currently, I'm loading the config from a dotenv file (`.env`).

**Comment by tonivj5** [comment]
> Perhaps the proper solution would be to update this modules usage documentation to cover this?

PR are welcome! :tada: However, it's an "issue" of typeorm properly

> This module should be an official option in typeorm because case sensitivity can be an issue (at least for tables) :-)

Totally! That was the reason because I created it primarily :+1:

> I understand that we have to import this module - sadly I'm using the typeorm CLI directly so this means that I would need to setup a "wrapper" or as you suggested, use a js config file.

typeorm cli has a `--config`, I think you could use it to point to a `.js` config where the naming strategy is imported...

Anyway, it's a typeorm's issue :disappointed:

**Comment by ofbeaton** [comment]
I just added:
```
const SnakeNamingStrategy = require('typeorm-naming-strategies').SnakeNamingStrategy 
const snakeNamingStrategy = new SnakeNamingStrategy();
```
To the top of my `ormconfig.js`, which I believe is picked up by the CLI as well. 

I also import my `dotenv` in it so it actually has no secrets/config in it, and it's all pulled from environment variables, and the `ormconfig.js` can be checked into VCS.

Wether or not this functionality should be part of typeorm...

How to correctly use this package so that it works with typeorm projects is not a typeorm issue, and this package should clearly explain how you can use it. No-one should have to go into the issues list to find out how to use this package.

**Comment by tonivj5** [comment]
Thanks for the tip @ofbeaton

> How to correctly use this package so that it works with typeorm projects is not a typeorm issue, and this package should clearly explain how you can use it. No-one should have to go into the issues list to find out how to use this package.

If typeorm hasn't documeneted how to use custom naming strategies in migrations, I think it's a typeorm's lack. This package only implements its interface.

Anyway, you can create a PR to document it if you want, they're very welcome :heart:

**Comment by tonivj5** [comment]
Hey @ofbeaton, @sanderlissenburg has fixed (:cupid:) this "doc missing" :+1:
